import test from 'node:test';
import assert from 'node:assert/strict';
import {parseEvent,parseTask,canonicalJson,fingerprint} from '../../packages/events/index.ts';
import {parseSaveCommand,assertRevision} from '../../packages/site-schema/index.ts';
import {authorize} from '../../packages/platform/authorization.ts';
import {transition,expiredLeaseOutcome,ownsLease} from '../../packages/platform/jobs.ts';
import {retryDelay,outcomeFromException} from '../../packages/adapter-sdk/index.ts';
export const A='11111111-1111-4111-8111-111111111111';
export const B='22222222-2222-4222-8222-222222222222';
export const C='33333333-3333-4333-8333-333333333333';
export const event={schemaVersion:1,eventId:C,tenantId:A,aggregateId:B,aggregateVersion:1,type:'site.lifecycle.v1',occurredAt:'2026-09-09T00:00:00Z',traceId:C,payload:{release:'artifact:test'}};
export const task={schemaVersion:1,jobId:B,tenantId:A,jobType:'publish.build',deadline:'2030-01-01T00:00:00Z',traceId:C};
test('valid event/task contracts are normalized',()=>{assert.equal(parseEvent(event).tenantId,A);assert.equal(parseTask(task).jobType,'publish.build');});
for(const [name,patch] of Object.entries({schema:{schemaVersion:2},uuid:{tenantId:'any'},type:{type:'arbitrary.topic'},revision:{aggregateVersion:1.5},time:{occurredAt:'tomorrow'}})) test(`event rejects ${name}`,()=>assert.throws(()=>parseEvent({...event,...patch})));
test('task rejects unknown worker types',()=>assert.throws(()=>parseTask({...task,jobType:'execute.shell'})));
test('canonical JSON is key-order-independent',async()=>assert.equal(await fingerprint({b:2,a:1}),await fingerprint({a:1,b:2})));
test('canonical JSON rejects cycles and nonfinite values',()=>{const x={};x.self=x;assert.throws(()=>canonicalJson(x));assert.throws(()=>canonicalJson({x:NaN}));});
test('canonical JSON enforces byte and property limits',()=>{assert.throws(()=>canonicalJson({x:'🙂'.repeat(100)},100));assert.throws(()=>canonicalJson(JSON.parse('{"__proto__":1}')));});
test('save contract preserves pages, settings and unknown editor fields',()=>{const editorData={pages:[{id:'home',elements:[]}],globalSettings:{font:'A'},futureField:{x:1}};const save=parseSaveCommand({websiteId:B,expectedRevision:3,idempotencyKey:'abcdefghijklmnop',editorData});assert.deepEqual(save.editorData,editorData);});
test('save rejects short idempotency keys',()=>assert.throws(()=>parseSaveCommand({websiteId:B,expectedRevision:0,idempotencyKey:'x',editorData:{}})));
test('stale revision is an explicit conflict',()=>{assert.doesNotThrow(()=>assertRevision(3,3));assert.throws(()=>assertRevision(4,3),/REVISION_CONFLICT/);});
test('membership grants are tenant-scoped',()=>{const m={tenantId:A,userId:C,role:'OWNER',status:'ACTIVE'};assert.doesNotThrow(()=>authorize(m,C,A,'site.publish'));assert.throws(()=>authorize(m,C,B,'site.publish'),/FORBIDDEN/);});
test('missing, suspended and insufficient membership fail closed',()=>{assert.throws(()=>authorize(null,C,A,'site.read'));assert.throws(()=>authorize({tenantId:A,userId:C,role:'VIEWER',status:'ACTIVE'},C,A,'site.edit'));assert.throws(()=>authorize({tenantId:A,userId:C,role:'OWNER',status:'SUSPENDED'},C,A,'site.read'));});
test('terminal and unknown jobs cannot silently retry',()=>{assert.equal(transition('RUNNING','SUCCEEDED'),'SUCCEEDED');assert.throws(()=>transition('SUCCEEDED','RUNNING'));assert.throws(()=>transition('OUTCOME_UNKNOWN','QUEUED'));});
test('expired non-idempotent leases need reconciliation',()=>{assert.equal(expiredLeaseOutcome('non-idempotent'),'OUTCOME_UNKNOWN');assert.equal(expiredLeaseOutcome('idempotent'),'RETRY_SCHEDULED');});
test('lease tokens and deadlines both fence writes',()=>{assert.equal(ownsLease('new','old',200,100),false);assert.equal(ownsLease('new','new',100,100),false);assert.equal(ownsLease('new','new',200,100),true);});
test('retry policy is bounded and respects retry-after',()=>{assert.equal(retryDelay(1,()=>0.5),500);assert.equal(retryDelay(100,()=>1),300000);assert.equal(retryDelay(1,()=>0,5000),5000);assert.throws(()=>retryDelay(0));});
test('uncertain external exceptions never become successful',()=>assert.equal(outcomeFromException('non-idempotent').status,'OUTCOME_UNKNOWN'));
